// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwayxkeeegskxhdogmwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3YXl4a2VlZWdza3hoZG9nbXdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDk2NzAsImV4cCI6MjA3MzYyNTY3MH0.MQP6-1Yo0xK9P-eaXqD7GYiQP6qVcEiJy5kdScZZtFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});